# -*- coding: utf-8 -*-
"""Создание таблиц в Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15zxigQqJd5HToGmc_SHPxme5Ld7aDF6c
"""

!pip install prettytable

from prettytable import PrettyTable

receipt = PrettyTable()
receipt.field_names = ['№', 'Продукт', 'Цена', 'Количество', 'Стоимость']

print(receipt)